### ISSUE TITLE
Allow changing the error website

### ISSUE THREAD

**Issue by niccokunzmann** [riad-azz/flask-allowedhosts#1]
I would like to be able to change the website that is displayed when the host is the wrong one.
The purpose is to serve documentation instead for the developer/hoster.

Code:

https://github.com/riad-azz/flask-allowedhosts/blob/eea498525d4a7ea9b29c5e52f2a6bbaeb0d62846/flask_allowedhosts/decorators.py#L43

This might serve as a solution:

https://flask.palletsprojects.com/en/2.1.x/errorhandling/#registering

It would be nice to have that in the documentation :)

**Comment by riad-azz** [comment]
Thanks for the feedback, I haven't touched this in a long while but I can make a solution for this. I will add an optional `on_denied` argument that you can use to override the default behavior:

```py
# If the host_name is None then use the client_ip to check
if client_ip in allowed_hosts:
    debug_log("Valid Client IP, request was permitted")
    return func(*args, **kwargs)
else:
    if callable(on_denied):
        return on_denied()
    else:
        # Abort request if all checks failed
        debug_log("Invalid Client IP, request was not permitted")
        abort(403)
```

So that you can use it in something like this:

```py
from flask import redirect

def redirect_to_docs():
    return redirect("docs.example.com/api/v1")

@app.route("/api/greet", methods=["GET"])
@limit_hosts(allowed_hosts=ALLOWED_HOSTS, on_denied=redirect_to_docs)
def greet_endpoint():
    name = request.args.get("name", "Friend")
    greeting = {"greeting": f"Hello There {name}!"}
    return jsonify(greeting), 200
```

and in this case it will redirect to the docs instead of showing the forbidden page.

this might take me some time because I haven't touched python in a while I don't quiet remember how to build a package haha, but i will do it.

**Comment by riad-azz** [comment]
The feature have been Added and you can check the new examples to see how you can add this in your project:

[flask-allowedhosts Redirect example](https://github.com/riad-azz/flask-allowedhosts/blob/main/examples/redirect/main.py)

have a great day!

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
I solved it for now with this one:

```
@app.errorhandler(403)
def host_not_allowed(error):
    return render_template(
        "403.html",
        hostname=request.host.split(':')[0],
        allowed_hosts=", ".join(ALLOWED_HOSTS)
        ), 403
```

**Comment by niccokunzmann** [comment]
Your hook is much better! I was probably too tired and did not read properly. Sorry!

**Comment by riad-azz** [comment]
You are welcome! glad to be of help
