### ISSUE TITLE
Hostname check with client IP hard to understand - is this a bug?

### ISSUE THREAD

**Issue by niccokunzmann** [riad-azz/flask-allowedhosts#2]
I limit the hostnames with this package.
When I request from the same IP, the limit works well.

When I am behind a proxy or I request from another IP address which is usual to do over the Internet if a service is running, then the client IP is resolved. It seems that this does not serve the purpose of the package.

Code:

https://github.com/niccokunzmann/flask-allowedhosts/blob/ee44db6305de350d6fb4ddf30020a0e7e9bbbc14/flask_allowedhosts/decorators.py#L23

# Case 1: Client and server on same IP

When I do this, limiting works nicely, as expected. I can request from different IPs and block others, like localhost.

# Case 2: Serving behind a proxy

When I serve behind a proxy, this is happening:

I request this website: test.open-web-calendar.hosted.quelltext.eu
The real host requesting it is the proxy: x-nginx-proxy-manager-1.x_owc-net

The host is invalid. The host header is set before the proxy, though.

```
open-web-calendar-test-1  | Client IP: 172.20.0.3
open-web-calendar-test-1  | Request HOST: test.open-web-calendar.hosted.quelltext.eu
open-web-calendar-test-1  | Real HOST: x-nginx-proxy-manager-1.x_owc-net
open-web-calendar-test-1  | Invalid HOST, falling back to Client IP check
open-web-calendar-test-1  | Invalid Client IP, request was not permitted
open-web-calendar-test-1  | 172.20.0.3 - - [10/May/2024 22:38:50] "GET / HTTP/1.1" 403 -
```

# Case 3: Docker container on same computer

The host is changed again, I believe:

![grafik](https://github.com/riad-azz/flask-allowedhosts/assets/564768/375f03e1-13d1-4198-8712-520eea621a0d)

```
$ docker run -d --rm -p 5000:5000 -e ALLOWED_HOSTS=172.17.0.3 niccokunzmann/open-web-calendar
$ docker inspect stupefied_lamarr
...
            "IPAddress": "172.17.0.3",

...
```

It seems like the client IP is checked for some reason. Would it be useful to check the server IPs instead?

See also: https://github.com/niccokunzmann/open-web-calendar/issues/371#issuecomment-2105354424

**Comment by riad-azz** [comment]
What's your desired outcome from using this package? I'm not sure about the behavior you're expecting. 

But I would like to help you, could you please explain what you're trying to achieve? 

also, providing a snippet of the code you are using or even dummy examples of how you're using it would be greatly appreciated.

**Comment by niccokunzmann** [comment]
What I would like to do is to do this:

## Case 2:

![grafik](https://github.com/riad-azz/flask-allowedhosts/assets/564768/db360a18-c880-4fee-99ae-be3604fc33b7)

In case 2, flask-allowedhosts checks the Nginx instance's IP address to test if the hostname is in the list but the request host is the correct one, see above:
```
Request HOST: test.open-web-calendar.hosted.quelltext.eu
```

http://test.open-web-calendar.hosted.quelltext.eu/ - runs this with `ALLOWED_HOSTS=test.open-web-calendar.hosted.quelltext.eu`


## Case 3:

![grafik](https://github.com/riad-azz/flask-allowedhosts/assets/564768/ca22d59e-e411-4722-aeed-c2e8576eb42d)

In this case, still, I GET the endpoint from a different client IP and I get the error, with the correct Host header that I expect.

Request:
```
nicco@ubuntu-4gb-fsn1-1:~$ wget -O- --header "Host: test.open-web-calendar.hosted.quelltext.eu" http://172.20.0.4
--2024-05-11 07:57:32--  http://172.20.0.4/
Connecting to 172.20.0.4:80... connected.
HTTP request sent, awaiting response... 403 FORBIDDEN
2024-05-11 07:57:32 ERROR 403: FORBIDDEN.
```

Logs:
```
nicco@ubuntu-4gb-fsn1-1:~$ docker compose logs open-web-calendar-test
open-web-calendar-test-1  | Client IP: 172.20.0.1
open-web-calendar-test-1  | Request HOST: test.open-web-calendar.hosted.quelltext.eu
open-web-calendar-test-1  | Real HOST: ubuntu-4gb-fsn1-1.local   # <---- This is my client IP address
open-web-calendar-test-1  | Invalid HOST, falling back to Client IP check
open-web-calendar-test-1  | Invalid Client IP, request was not permitted
open-web-calendar-test-1  | 172.20.0.1 - - [11/May/2024 07:57:01] "GET / HTTP/1.1" 403 -
```

---

So, I think, I would like this module host to check the host header. 

My guess about this line:
https://github.com/riad-azz/flask-allowedhosts/blob/ee44db6305de350d6fb4ddf30020a0e7e9bbbc14/flask_allowedhosts/decorators.py#L17

Is that in case someone requests the IP address instead of the host name, then this is looked up and one sees if it matches. What it does on case 2 and 3 which are production cases, is that the IP of the client is used and not the IP of the server.

I would basically remove this line if I could in order to just test the host header. 
But why am I writing this: https://github.com/niccokunzmann/open-web-calendar/pull/366 has been made to mitigate [host header injections](https://portswigger.net/web-security/host-header) and if this module could claim that it helps with this use-case, that would be very nice!
Right now, I cannot use it in production behind a proxy server. I can only use it if I am working on the same machine as the flask app.

What are your thoughts on this?

**Comment by riad-azz** [comment]
Okay now I think I understand what you are trying to achieve. Try to use this modified decorator where it only checks the host header and you can also use `host:port` or `host` format on this one,  just copy paste it in your project the package is not needed:

```py
# Flask modules
from flask import request, abort

# Other modules
from typing import Callable
from functools import wraps

DEBUG = True


def debug_log(message: str):
    if not DEBUG:
        return

    print(message)


def limit_hosts(allowed_hosts: list = None, on_denied: Callable = None):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            if allowed_hosts is None or len(allowed_hosts) == 0:
                return func(*args, **kwargs)

            host_name = request.host
            is_host_allowed = host_name in allowed_hosts
            if not is_host_allowed:
                if callable(on_denied):
                    debug_log(f"Host {host_name} is not allowed, calling on_denied")
                    return on_denied(*args, **kwargs)
                else:
                    # Abort request if all checks failed
                    debug_log(f"Host {host_name} is not allowed, aborting")
                    abort(403)

            debug_log(f"Host {host_name} is allowed, request proceeding")
            return func(*args, **kwargs)

        return wrapper

    return decorator
```

and you can use it the same as before:

```py
from flask import Flask, jsonify, request
from decorators import limit_hosts

ALLOWED_HOSTS = ["localhost:5000"]

app = Flask(__name__)


def on_denied():
    error = {"error": f"Host '{request.host}' is not allowed"}
    return jsonify(error), 403


@app.route("/")
@limit_hosts(allowed_hosts=ALLOWED_HOSTS, on_denied=on_denied)
def index():
    return "Hello, World!"


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
```

- This is the outcome if the host header in the request is not included in the `allowed_hosts` list:

![host-modified](https://github.com/riad-azz/flask-allowedhosts/assets/80968727/a964c8c2-f0ab-4732-a617-c9a7bb2c5b23)

is this what you were looking for?

**Comment by riad-azz** [comment]
should be addressed by: https://github.com/riad-azz/flask-allowed-hosts/commit/e663e70363cb007df3f83b7a05e4861027233ba7

**Comment by niccokunzmann** [comment]
I do not know how https://github.com/riad-azz/flask-allowed-hosts/commit/e663e70363cb007df3f83b7a05e4861027233ba7 solves the problem. As I understand it, it looks look up the client IP. However, I would just like to make sure that the host header matches. How does this relate to the client IP. Could you help me understand?

**Comment by riad-azz** [comment]
The Host header can be easily spoofed and therefore cannot be trusted. Instead, we verify the request by checking the client's IP address. If the client IP address matches one of IPs that belong to any host from the allowed hosts in our list:
```py
def get_hostname_ips(self, host: str) -> List[str]:
        try:
            host = socket.gethostbyname_ex(host)
            self.debug_log(f"Host: {host}")
            host_ips = host[2] # <- this is a list of the IP's that belong to the host name we provide
            self.debug_log(f"Host IPs: {host_ips}")
            return host_ips
        except socket.gaierror:
            self.debug_log(f"get_hostname_ips error: {host}")
            return []
```

We can determine that the request is valid and can be allowed. This approach is more secure because it relies on the actual source of the request rather than potentially manipulated data.

**Comment by niccokunzmann** [comment]
Oh! I was wondering... Now I understand! It is not allowed hosts - it is allowed clients! Did I understand this right?

Anyway, this lead to my documentation: https://open-web-calendar.quelltext.eu/host/configure/#allowed_hosts
And someone contributed this Pull Request: https://github.com/niccokunzmann/open-web-calendar/pull/366

So, I wonder if I even describe the functionality correctly ... I will open an issue to check that.

**Comment by riad-azz** [comment]
It works with both hostnames and IP addresses. Simply put, it is used to limit access to your API from unknown sources.

While CORS works in browsers to prevent access from unauthorized origins, it doesn't protect against non-browser requests. This package addresses that limitation by allowing only the hostnames/IPs in the `allowed_hosts` list to access the specified endpoint.
