### ISSUE TITLE
Vulnerability in the library

### ISSUE THREAD

**Issue by b0-n0-b0** [riad-azz/flask-allowedhosts#3]
Hi! I wanted to reach out on twitter but your settings are currently forbidding DMs
I wanted to discuss about a vulnerability on this library
Where should we talk about that?

**Comment by riad-azz** [comment]
thanks for reaching out! feel free to start a new issue in this repository, or if you already have a fix in mind, you are welcome to open a pull request and I would be happy to discuss and review it there
