### ISSUE TITLE
Create limit_hosts again

### ISSUE THREAD

**Issue by niccokunzmann** [riad-azz/flask-allowedhosts#5]
```python
@limit_hosts(allowed_hosts=ALLOWED_HOSTS)
```

It would be relatively easy to maintain the old API.
If you add the `limit_hosts` again, projects can update easily and they do not have to go though much trouble, especially if it is in unmaintained 3rd party code.

To solve this issue, add a shortcut-function again for `limit_hosts()`.

Thanks for the update!

**Comment by riad-azz** [comment]
Yeah, it shouldn't be a problem. The decorator can be added back for backward compatibility. 

I will be adding this either today or tomorrow.

**Comment by riad-azz** [comment]
legacy `limit_hosts` has been added in : https://github.com/riad-azz/flask-allowed-hosts/commit/545b5fd1dc4136c1014ea56fa2af4780de8a0d21
