### ISSUE TITLE
Output in version 1.1.1

### ISSUE THREAD

**Issue by niccokunzmann** [riad-azz/flask-allowedhosts#6]
In the new version, I can see this being printed though my test cases:

```
Flask Allowed Hosts -> All hosts are allowed, request was permitted.
```

I did not switch on debug information. 

> You can enable debug mode by setting the ALLOWED_HOSTS_DEBUG environment variable to True:
> export ALLOWED_HOSTS_DEBUG="True"
> This will print helpful debug messages to the console.

I did not set that but it still prints it. Is this based on the general `debug` flag?
I would like to not see it by default.

**Comment by riad-azz** [comment]
fixed by: https://github.com/riad-azz/flask-allowed-hosts/pull/7

**Comment by riad-azz** [comment]
adjusted to make sure debug mode is only enabled when set to `True` as documented : https://github.com/riad-azz/flask-allowed-hosts/commit/243a6166c96f4a17c215cc75b03cf6ba931f2da7
